language: android
sudo: required
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=24.0.2
  - ADB_INSTALL_TIMEOUT=5
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
before_script:
 - chmod +x gradlew
script:
- ./gradlew build --stacktrace